name: foodgo
description:

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.4
  provider: ^6.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.4
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  image_picker: ^1.2.0
  crypto: ^3.0.3
  font_awesome_flutter: ^10.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

  uses-material-design: true
  assets:
    - assets/
    - assets/doAn/
    - assets/logo/
    - assets/voucher/
    - .env
    - assets/icons/
    - assets/data/
