// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAolfyUmGAWhKwQKt2zGXbH7f5tHfScAmI',
    appId: '1:720550468957:web:ae732f7efa57baeae49cb4',
    messagingSenderId: '720550468957',
    projectId: 'foodgo-app-5122d',
    authDomain: 'foodgo-app-5122d.firebaseapp.com',
    storageBucket: 'foodgo-app-5122d.firebasestorage.app',
    measurementId: 'G-WGXQCXE5X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg0uJg-XV45V2Dn_YM9eiyuK7KBlgWd4A',
    appId: '1:720550468957:android:c718d32b8da89942e49cb4',
    messagingSenderId: '720550468957',
    projectId: 'foodgo-app-5122d',
    storageBucket: 'foodgo-app-5122d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7tLYXk6tGdBUv3oIVK22u81obK2dLaI',
    appId: '1:720550468957:ios:975f1562f8e6e2b7e49cb4',
    messagingSenderId: '720550468957',
    projectId: 'foodgo-app-5122d',
    storageBucket: 'foodgo-app-5122d.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAolfyUmGAWhKwQKt2zGXbH7f5tHfScAmI',
    appId: '1:720550468957:web:bd48a757b215d195e49cb4',
    messagingSenderId: '720550468957',
    projectId: 'foodgo-app-5122d',
    authDomain: 'foodgo-app-5122d.firebaseapp.com',
    storageBucket: 'foodgo-app-5122d.firebasestorage.app',
    measurementId: 'G-6KTC3VKW39',
  );
}
